POST http://localhost:3000/api/authors
Content-Type: application/json

{
  "name": ""
}

### 

GET http://localhost:3000/api/authors

###

GET http://localhost:3000/api/authors/:id

###

PATCH http://localhost:3000/api/authors/:id
Content-Type: application/json

{
  "name": ""
}

###

DELETE http://localhost:3000/api/authors/:id

###

POST http://localhost:3000/api/genres
Content-Type: application/json

{
  "name": ""
}

### 

GET http://localhost:3000/api/genres

###

GET http://localhost:3000/api/genres/:id

###

PATCH http://localhost:3000/api/genres/:id
Content-Type: application/json

{
  "name": ""
}

###

DELETE http://localhost:3000/api/genres/:id

###

GET http://localhost:3000/api/books

###

POST http://localhost:3000/api/books
Content-Type: application/json

{
  "authorId": "",
  "genreId": "",
  "title": "",
  "publicationYear": 2024,
  "isbn": "",
  "availableCopies": 100
}

###

GET http://localhost:3000/api/books/f2592e8b-87ce-491b-aa77-6dc832ec0818


###

PATCH http://localhost:3000/api/books/f2592e8b-87ce-491b-aa77-6dc832ec0818
Content-Type: application/json

{
  "title": ""
}

###

DELETE http://localhost:3000/api/books/f2592e8b-87ce-491b-aa77-6dc832ec0818

###

GET http://localhost:3000/api/borrowers

###

POST http://localhost:3000/api/borrowers
Content-Type: application/json

{
  "name": "",
  "email": ""
}

###

GET http://localhost:3000/api/borrowers/:id

###

PATCH http://localhost:3000/api/borrowers/:id
Content-Type: application/json

{
  
}

###

DELETE http://localhost:3000/api/borrowers/:id

###

GET http://localhost:3000/api/transactions

###

POST http://localhost:3000/api/transactions
Content-Type: application/json

{
  "bookId": "",
  "borrowerId": "",
  "borrowPeriod": 7
}

###

GET http://localhost:3000/api/transactions/:id

###

PATCH http://localhost:3000/api/transactions/:id
Content-Type: application/json

{
  "returnDate": ""
}

###

DELETE http://localhost:3000/api/transactions/:id