POST https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/authors
Content-Type: application/json

{
  "name": ""
}

### 

GET https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/authors

###

GET https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/authors/:id

###

PATCH https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/authors/:id
Content-Type: application/json

{
  "name": ""
}

###

DELETE https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/authors/:id

###

POST https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/genres
Content-Type: application/json

{
  "name": ""
}

### 

GET https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/genres

###

GET https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/genres/:id

###

PATCH https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/genres/:id
Content-Type: application/json

{
  "name": ""
}

###

DELETE https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/genres/:id

###

GET https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/books

###

POST https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/books
Content-Type: application/json

{
  "authorId": "",
  "genreId": "",
  "title": "",
  "publicationYear": 2024,
  "isbn": "",
  "availableCopies": 100
}

###

GET https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/books/f2592e8b-87ce-491b-aa77-6dc832ec0818


###

PATCH https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/books/f2592e8b-87ce-491b-aa77-6dc832ec0818
Content-Type: application/json

{
  "title": ""
}

###

DELETE https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/books/f2592e8b-87ce-491b-aa77-6dc832ec0818

###

GET https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/borrowers

###

POST https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/borrowers
Content-Type: application/json

{
  "name": "",
  "email": ""
}

###

GET https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/borrowers/:id

###

PATCH https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/borrowers/:id
Content-Type: application/json

{
  
}

###

DELETE https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/borrowers/:id

###

GET https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/transactions

###

POST https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/transactions
Content-Type: application/json

{
  "bookId": "",
  "borrowerId": "",
  "borrowPeriod": 7
}

###

GET https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/transactions/:id

###

PATCH https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/transactions/:id
Content-Type: application/json

{
  "returnDate": ""
}

###

DELETE https://bookstack-8j1h0znbc-ericjmoliveiras-projects.vercel.app/transactions/:id