version: '3.8'
services:
  db:
    image: 'postgres:latest'
    container_name: 'pg-nest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
      - POSTGRES_PASSWORD=randompassword
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
